#!/usr/bin/env bash
# Installs and configures HAProxy

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7143-web-01 44.201.180.86:80 check
    server 7143-web-02 3.82.249.245:80 check
EOF

service haproxy restart
