#!/usr/bin/env bash
# Installs HAProxy on a fresh Ubuntu box and configures it to load balance
# HTTP traffic between web-01 and web-02 using a round-robin algorithm.

apt-get update -y
apt-get install -y haproxy

# Let HAProxy be managed as a service
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 7143-web-01 44.201.180.86:80 check
    server 7143-web-02 3.82.249.245:80 check
EOF

service haproxy restart
